/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsultaRouteImport } from './routes/Consulta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolicitudesMedidorExtraRouteImport } from './routes/(Solicitudes)/MedidorExtra'
import { Route as SolicitudesDesconexionMedidorRouteImport } from './routes/(Solicitudes)/DesconexionMedidor'
import { Route as SolicitudesCambiomedidorRouteImport } from './routes/(Solicitudes)/Cambiomedidor'
import { Route as SolicitudesAsociadoRouteImport } from './routes/(Solicitudes)/Asociado'
import { Route as SolicitudesAfiliacionRouteImport } from './routes/(Solicitudes)/Afiliacion'
import { Route as ContactoSugerenciasRouteImport } from './routes/(Contacto)/Sugerencias'
import { Route as ContactoReportesRouteImport } from './routes/(Contacto)/Reportes'
import { Route as ContactoQuejasRouteImport } from './routes/(Contacto)/Quejas'
import { Route as AboutUsHistoriaRouteImport } from './routes/(AboutUs)/Historia'
import { Route as AboutUsCalidadAguaRouteImport } from './routes/(AboutUs)/CalidadAgua'

const ConsultaRoute = ConsultaRouteImport.update({
  id: '/Consulta',
  path: '/Consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesMedidorExtraRoute = SolicitudesMedidorExtraRouteImport.update({
  id: '/(Solicitudes)/MedidorExtra',
  path: '/MedidorExtra',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesDesconexionMedidorRoute =
  SolicitudesDesconexionMedidorRouteImport.update({
    id: '/(Solicitudes)/DesconexionMedidor',
    path: '/DesconexionMedidor',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolicitudesCambiomedidorRoute =
  SolicitudesCambiomedidorRouteImport.update({
    id: '/(Solicitudes)/Cambiomedidor',
    path: '/Cambiomedidor',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolicitudesAsociadoRoute = SolicitudesAsociadoRouteImport.update({
  id: '/(Solicitudes)/Asociado',
  path: '/Asociado',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesAfiliacionRoute = SolicitudesAfiliacionRouteImport.update({
  id: '/(Solicitudes)/Afiliacion',
  path: '/Afiliacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoSugerenciasRoute = ContactoSugerenciasRouteImport.update({
  id: '/(Contacto)/Sugerencias',
  path: '/Sugerencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoReportesRoute = ContactoReportesRouteImport.update({
  id: '/(Contacto)/Reportes',
  path: '/Reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoQuejasRoute = ContactoQuejasRouteImport.update({
  id: '/(Contacto)/Quejas',
  path: '/Quejas',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsHistoriaRoute = AboutUsHistoriaRouteImport.update({
  id: '/(AboutUs)/Historia',
  path: '/Historia',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsCalidadAguaRoute = AboutUsCalidadAguaRouteImport.update({
  id: '/(AboutUs)/CalidadAgua',
  path: '/CalidadAgua',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Consulta': typeof ConsultaRoute
  '/CalidadAgua': typeof AboutUsCalidadAguaRoute
  '/Historia': typeof AboutUsHistoriaRoute
  '/Quejas': typeof ContactoQuejasRoute
  '/Reportes': typeof ContactoReportesRoute
  '/Sugerencias': typeof ContactoSugerenciasRoute
  '/Afiliacion': typeof SolicitudesAfiliacionRoute
  '/Asociado': typeof SolicitudesAsociadoRoute
  '/Cambiomedidor': typeof SolicitudesCambiomedidorRoute
  '/DesconexionMedidor': typeof SolicitudesDesconexionMedidorRoute
  '/MedidorExtra': typeof SolicitudesMedidorExtraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Consulta': typeof ConsultaRoute
  '/CalidadAgua': typeof AboutUsCalidadAguaRoute
  '/Historia': typeof AboutUsHistoriaRoute
  '/Quejas': typeof ContactoQuejasRoute
  '/Reportes': typeof ContactoReportesRoute
  '/Sugerencias': typeof ContactoSugerenciasRoute
  '/Afiliacion': typeof SolicitudesAfiliacionRoute
  '/Asociado': typeof SolicitudesAsociadoRoute
  '/Cambiomedidor': typeof SolicitudesCambiomedidorRoute
  '/DesconexionMedidor': typeof SolicitudesDesconexionMedidorRoute
  '/MedidorExtra': typeof SolicitudesMedidorExtraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Consulta': typeof ConsultaRoute
  '/(AboutUs)/CalidadAgua': typeof AboutUsCalidadAguaRoute
  '/(AboutUs)/Historia': typeof AboutUsHistoriaRoute
  '/(Contacto)/Quejas': typeof ContactoQuejasRoute
  '/(Contacto)/Reportes': typeof ContactoReportesRoute
  '/(Contacto)/Sugerencias': typeof ContactoSugerenciasRoute
  '/(Solicitudes)/Afiliacion': typeof SolicitudesAfiliacionRoute
  '/(Solicitudes)/Asociado': typeof SolicitudesAsociadoRoute
  '/(Solicitudes)/Cambiomedidor': typeof SolicitudesCambiomedidorRoute
  '/(Solicitudes)/DesconexionMedidor': typeof SolicitudesDesconexionMedidorRoute
  '/(Solicitudes)/MedidorExtra': typeof SolicitudesMedidorExtraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Consulta'
    | '/CalidadAgua'
    | '/Historia'
    | '/Quejas'
    | '/Reportes'
    | '/Sugerencias'
    | '/Afiliacion'
    | '/Asociado'
    | '/Cambiomedidor'
    | '/DesconexionMedidor'
    | '/MedidorExtra'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Consulta'
    | '/CalidadAgua'
    | '/Historia'
    | '/Quejas'
    | '/Reportes'
    | '/Sugerencias'
    | '/Afiliacion'
    | '/Asociado'
    | '/Cambiomedidor'
    | '/DesconexionMedidor'
    | '/MedidorExtra'
  id:
    | '__root__'
    | '/'
    | '/Consulta'
    | '/(AboutUs)/CalidadAgua'
    | '/(AboutUs)/Historia'
    | '/(Contacto)/Quejas'
    | '/(Contacto)/Reportes'
    | '/(Contacto)/Sugerencias'
    | '/(Solicitudes)/Afiliacion'
    | '/(Solicitudes)/Asociado'
    | '/(Solicitudes)/Cambiomedidor'
    | '/(Solicitudes)/DesconexionMedidor'
    | '/(Solicitudes)/MedidorExtra'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultaRoute: typeof ConsultaRoute
  AboutUsCalidadAguaRoute: typeof AboutUsCalidadAguaRoute
  AboutUsHistoriaRoute: typeof AboutUsHistoriaRoute
  ContactoQuejasRoute: typeof ContactoQuejasRoute
  ContactoReportesRoute: typeof ContactoReportesRoute
  ContactoSugerenciasRoute: typeof ContactoSugerenciasRoute
  SolicitudesAfiliacionRoute: typeof SolicitudesAfiliacionRoute
  SolicitudesAsociadoRoute: typeof SolicitudesAsociadoRoute
  SolicitudesCambiomedidorRoute: typeof SolicitudesCambiomedidorRoute
  SolicitudesDesconexionMedidorRoute: typeof SolicitudesDesconexionMedidorRoute
  SolicitudesMedidorExtraRoute: typeof SolicitudesMedidorExtraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Consulta': {
      id: '/Consulta'
      path: '/Consulta'
      fullPath: '/Consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Solicitudes)/MedidorExtra': {
      id: '/(Solicitudes)/MedidorExtra'
      path: '/MedidorExtra'
      fullPath: '/MedidorExtra'
      preLoaderRoute: typeof SolicitudesMedidorExtraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Solicitudes)/DesconexionMedidor': {
      id: '/(Solicitudes)/DesconexionMedidor'
      path: '/DesconexionMedidor'
      fullPath: '/DesconexionMedidor'
      preLoaderRoute: typeof SolicitudesDesconexionMedidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Solicitudes)/Cambiomedidor': {
      id: '/(Solicitudes)/Cambiomedidor'
      path: '/Cambiomedidor'
      fullPath: '/Cambiomedidor'
      preLoaderRoute: typeof SolicitudesCambiomedidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Solicitudes)/Asociado': {
      id: '/(Solicitudes)/Asociado'
      path: '/Asociado'
      fullPath: '/Asociado'
      preLoaderRoute: typeof SolicitudesAsociadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Solicitudes)/Afiliacion': {
      id: '/(Solicitudes)/Afiliacion'
      path: '/Afiliacion'
      fullPath: '/Afiliacion'
      preLoaderRoute: typeof SolicitudesAfiliacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Contacto)/Sugerencias': {
      id: '/(Contacto)/Sugerencias'
      path: '/Sugerencias'
      fullPath: '/Sugerencias'
      preLoaderRoute: typeof ContactoSugerenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Contacto)/Reportes': {
      id: '/(Contacto)/Reportes'
      path: '/Reportes'
      fullPath: '/Reportes'
      preLoaderRoute: typeof ContactoReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Contacto)/Quejas': {
      id: '/(Contacto)/Quejas'
      path: '/Quejas'
      fullPath: '/Quejas'
      preLoaderRoute: typeof ContactoQuejasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(AboutUs)/Historia': {
      id: '/(AboutUs)/Historia'
      path: '/Historia'
      fullPath: '/Historia'
      preLoaderRoute: typeof AboutUsHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(AboutUs)/CalidadAgua': {
      id: '/(AboutUs)/CalidadAgua'
      path: '/CalidadAgua'
      fullPath: '/CalidadAgua'
      preLoaderRoute: typeof AboutUsCalidadAguaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultaRoute: ConsultaRoute,
  AboutUsCalidadAguaRoute: AboutUsCalidadAguaRoute,
  AboutUsHistoriaRoute: AboutUsHistoriaRoute,
  ContactoQuejasRoute: ContactoQuejasRoute,
  ContactoReportesRoute: ContactoReportesRoute,
  ContactoSugerenciasRoute: ContactoSugerenciasRoute,
  SolicitudesAfiliacionRoute: SolicitudesAfiliacionRoute,
  SolicitudesAsociadoRoute: SolicitudesAsociadoRoute,
  SolicitudesCambiomedidorRoute: SolicitudesCambiomedidorRoute,
  SolicitudesDesconexionMedidorRoute: SolicitudesDesconexionMedidorRoute,
  SolicitudesMedidorExtraRoute: SolicitudesMedidorExtraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
